"""initial_schema"""
from alembic import op
import sqlalchemy as sa

revision = '7efbed15324a'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depots',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('idempotency_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('command_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.String(length=64), nullable=True),
    sa.Column('request_metadata', sa.JSON(), nullable=True),
    sa.Column('result_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotency_records_key'), 'idempotency_records', ['key'], unique=True)
    op.create_table('planning_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('planning_date', sa.Date(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('runtime_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planning_runs_planning_date'), 'planning_runs', ['planning_date'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('outlets',
    sa.Column('outlet_id', sa.String(length=32), nullable=False),
    sa.Column('brand', sa.String(length=16), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=False),
    sa.Column('depot_code', sa.String(length=32), nullable=False),
    sa.Column('dock_type', sa.String(length=32), nullable=False),
    sa.Column('parking_constraint', sa.String(length=32), nullable=False),
    sa.Column('mall_window', sa.String(length=80), nullable=True),
    sa.Column('window_open_time', sa.String(length=8), nullable=True),
    sa.Column('window_close_time', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['depot_code'], ['depots.code'], ),
    sa.PrimaryKeyConstraint('outlet_id')
    )
    op.create_index(op.f('ix_outlets_brand'), 'outlets', ['brand'], unique=False)
    op.create_index(op.f('ix_outlets_depot_code'), 'outlets', ['depot_code'], unique=False)
    op.create_index(op.f('ix_outlets_district'), 'outlets', ['district'], unique=False)
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('temp', sa.String(length=16), nullable=False),
    sa.Column('weight_cap_kg', sa.Float(), nullable=False),
    sa.Column('volume_cap_m3', sa.Float(), nullable=False),
    sa.Column('fuel_type', sa.String(length=24), nullable=False),
    sa.Column('km_per_l', sa.Float(), nullable=False),
    sa.Column('weekly_fuel_quota_l', sa.Float(), nullable=False),
    sa.Column('depot_code', sa.String(length=32), nullable=False),
    sa.CheckConstraint('volume_cap_m3 > 0'),
    sa.CheckConstraint('weight_cap_kg > 0'),
    sa.ForeignKeyConstraint(['depot_code'], ['depots.code'], ),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    op.create_index(op.f('ix_vehicles_depot_code'), 'vehicles', ['depot_code'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('outlet_id', sa.String(length=32), nullable=False),
    sa.Column('requested_delivery_date', sa.Date(), nullable=False),
    sa.Column('temperature_requirement', sa.String(length=16), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('volume_m3', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cutoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('units >= 0'),
    sa.CheckConstraint('volume_m3 >= 0'),
    sa.CheckConstraint('weight_kg >= 0'),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.outlet_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_orders_outlet_id'), 'orders', ['outlet_id'], unique=False)
    op.create_index(op.f('ix_orders_requested_delivery_date'), 'orders', ['requested_delivery_date'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.String(length=32), nullable=True),
    sa.Column('depot_code', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['depot_code'], ['depots.code'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.outlet_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('old_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_aggregate_id'), 'audit_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_audit_events_aggregate_type'), 'audit_events', ['aggregate_type'], unique=False)
    op.create_table('plan_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('planning_run_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('input_digest', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['planning_run_id'], ['planning_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planning_run_id', 'version_number')
    )
    op.create_index(op.f('ix_plan_versions_planning_run_id'), 'plan_versions', ['planning_run_id'], unique=False)
    op.create_table('deferrals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('plan_version_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=80), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['plan_version_id'], ['plan_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_version_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=32), nullable=False),
    sa.Column('trip_number', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=16), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_version_id'], ['plan_versions.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_version_id', 'trip_number')
    )
    op.create_index(op.f('ix_trips_plan_version_id'), 'trips', ['plan_version_id'], unique=False)
    op.create_index(op.f('ix_trips_vehicle_id'), 'trips', ['vehicle_id'], unique=False)
    op.create_table('manifest_checks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('expected_quantity', sa.Integer(), nullable=False),
    sa.Column('loaded_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shortfalls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shortfalls_status'), 'shortfalls', ['status'], unique=False)
    op.create_index(op.f('ix_shortfalls_trip_id'), 'shortfalls', ['trip_id'], unique=False)
    op.create_table('trip_stops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('planned_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_service_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'order_id'),
    sa.UniqueConstraint('trip_id', 'sequence_number')
    )
    op.create_index(op.f('ix_trip_stops_order_id'), 'trip_stops', ['order_id'], unique=False)
    op.create_index(op.f('ix_trip_stops_trip_id'), 'trip_stops', ['trip_id'], unique=False)
    op.create_table('delivery_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_stop_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('server_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('command_ref', sa.String(length=128), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['trip_stop_id'], ['trip_stops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_events_trip_stop_id'), 'delivery_events', ['trip_stop_id'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('trip_stop_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confirmed_by_id', sa.Uuid(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['trip_stop_id'], ['trip_stops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('delivery_issues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('receipt_id', sa.Uuid(), nullable=True),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('issue_type', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reported_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proofs_of_delivery',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_stop_id', sa.Uuid(), nullable=False),
    sa.Column('delivery_event_id', sa.Uuid(), nullable=True),
    sa.Column('receiver_name', sa.String(length=120), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('object_ref', sa.String(length=255), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('mime_type', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_event_id'], ['delivery_events.id'], ),
    sa.ForeignKeyConstraint(['trip_stop_id'], ['trip_stops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proofs_of_delivery')
    op.drop_table('delivery_issues')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_delivery_events_trip_stop_id'), table_name='delivery_events')
    op.drop_table('delivery_events')
    op.drop_index(op.f('ix_trip_stops_trip_id'), table_name='trip_stops')
    op.drop_index(op.f('ix_trip_stops_order_id'), table_name='trip_stops')
    op.drop_table('trip_stops')
    op.drop_index(op.f('ix_shortfalls_trip_id'), table_name='shortfalls')
    op.drop_index(op.f('ix_shortfalls_status'), table_name='shortfalls')
    op.drop_table('shortfalls')
    op.drop_table('manifest_checks')
    op.drop_index(op.f('ix_trips_vehicle_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_plan_version_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_table('deferrals')
    op.drop_index(op.f('ix_plan_versions_planning_run_id'), table_name='plan_versions')
    op.drop_table('plan_versions')
    op.drop_index(op.f('ix_audit_events_aggregate_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_aggregate_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_requested_delivery_date'), table_name='orders')
    op.drop_index(op.f('ix_orders_outlet_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_vehicles_depot_code'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_outlets_district'), table_name='outlets')
    op.drop_index(op.f('ix_outlets_depot_code'), table_name='outlets')
    op.drop_index(op.f('ix_outlets_brand'), table_name='outlets')
    op.drop_table('outlets')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_planning_runs_planning_date'), table_name='planning_runs')
    op.drop_table('planning_runs')
    op.drop_index(op.f('ix_idempotency_records_key'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_table('depots')
    # ### end Alembic commands ###
